# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'c286be15-3a3a-43e4-b6be-d9602b81ea31'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'mustafiz-rg'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName AzureRmPipeline-repo -linkedTemplateUri https://raw.githubusercontent.com/mustak09mbstu/AzureRmPipeline-repo/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'


